import { Pool } from "pg";
import type { ChannelFilters, ChatMessage, Platform } from "@/lib/types";
import { publishChatMessage } from "@/lib/chat-events";

const databaseUrl = process.env.DATABASE_URL;
const supabaseUrl = process.env.SUPABASE_URL?.replace(/\/$/, "");
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

export const dbConfigured = Boolean(databaseUrl || (supabaseUrl && supabaseKey));
export const dbProvider = databaseUrl ? "render-postgres" : supabaseUrl && supabaseKey ? "supabase" : "demo";

let pool: Pool | null = null;
let schemaPromise: Promise<void> | null = null;

function getPool() {
  if (!databaseUrl) return null;
  if (!pool) pool = new Pool({ connectionString: databaseUrl, max: 5 });
  return pool;
}

async function ensurePgSchema() {
  const pg = getPool();
  if (!pg) return;
  if (!schemaPromise) {
    schemaPromise = (async () => {
      await pg.query(`
        create table if not exists chat_messages (
          id bigint generated by default as identity primary key,
          platform text not null check (platform in ('twitch', 'kick', 'youtube')),
          platform_message_id text not null,
          channel_id text,
          author_id text,
          author_name text not null,
          author_avatar text,
          author_color text,
          message text not null,
          message_type text not null default 'text',
          badges jsonb not null default '[]'::jsonb,
          created_at timestamptz not null,
          raw jsonb,
          inserted_at timestamptz not null default now(),
          unique (platform, platform_message_id)
        );
        create index if not exists chat_messages_created_at_idx on chat_messages (created_at desc);
        create index if not exists chat_messages_platform_channel_idx on chat_messages (platform, channel_id, id desc);
        create table if not exists platform_state (
          key text primary key,
          value jsonb not null default '{}'::jsonb,
          updated_at timestamptz not null default now()
        );
      `);
    })().catch((error) => {
      schemaPromise = null;
      throw error;
    });
  }
  await schemaPromise;
}

async function supabaseFetch(path: string, init: RequestInit = {}) {
  if (!supabaseUrl || !supabaseKey) throw new Error("Banco não configurado.");
  const res = await fetch(`${supabaseUrl}/rest/v1/${path}`, {
    ...init,
    cache: "no-store",
    headers: {
      apikey: supabaseKey,
      Authorization: `Bearer ${supabaseKey}`,
      "Content-Type": "application/json",
      ...(init.headers || {}),
    },
  });
  if (!res.ok) throw new Error(`Supabase ${res.status}: ${await res.text()}`);
  return res;
}

export async function insertMessages(messages: ChatMessage[]) {
  if (!messages.length) return;
  if (!dbConfigured) {
    for (const message of messages) publishChatMessage(message);
    return;
  }

  const pg = getPool();
  if (pg) {
    await ensurePgSchema();
    const params: unknown[] = [];
    const rows = messages.map((message, index) => {
      const base = index * 12;
      params.push(
        message.platform,
        message.platform_message_id,
        message.channel_id,
        message.author_id,
        message.author_name,
        message.author_avatar,
        message.author_color,
        message.message,
        message.message_type,
        JSON.stringify(message.badges || []),
        message.created_at,
        JSON.stringify(message.raw ?? null),
      );
      return `($${base + 1},$${base + 2},$${base + 3},$${base + 4},$${base + 5},$${base + 6},$${base + 7},$${base + 8},$${base + 9},$${base + 10}::jsonb,$${base + 11},$${base + 12}::jsonb)`;
    });

    await pg.query(
      `insert into chat_messages (
        platform, platform_message_id, channel_id, author_id, author_name,
        author_avatar, author_color, message, message_type, badges, created_at, raw
      ) values ${rows.join(",")}
      on conflict (platform, platform_message_id) do nothing`,
      params,
    );

    for (const message of messages) publishChatMessage(message);
    return;
  }

  const res = await fetch(`${supabaseUrl}/rest/v1/chat_messages?on_conflict=platform,platform_message_id`, {
    method: "POST",
    cache: "no-store",
    headers: {
      apikey: supabaseKey!,
      Authorization: `Bearer ${supabaseKey}`,
      "Content-Type": "application/json",
      Prefer: "resolution=ignore-duplicates,return=minimal",
    },
    body: JSON.stringify(messages),
  });
  if (!res.ok && res.status !== 409) {
    throw new Error(`Falha ao gravar mensagens: ${res.status} ${await res.text()}`);
  }

  for (const message of messages) publishChatMessage(message);
}

export async function insertMessage(message: ChatMessage) {
  await insertMessages([message]);
}

export async function upsertEnrichedMessages(messages: ChatMessage[]) {
  if (!messages.length) return;

  if (!dbConfigured) {
    for (const message of messages) publishChatMessage(message);
    return;
  }

  const pg = getPool();
  if (pg) {
    await ensurePgSchema();
    const params: unknown[] = [];
    const rows = messages.map((message, index) => {
      const base = index * 12;
      params.push(
        message.platform,
        message.platform_message_id,
        message.channel_id,
        message.author_id,
        message.author_name,
        message.author_avatar,
        message.author_color,
        message.message,
        message.message_type,
        JSON.stringify(message.badges || []),
        message.created_at,
        JSON.stringify(message.raw ?? null),
      );
      return `(${base + 1},${base + 2},${base + 3},${base + 4},${base + 5},${base + 6},${base + 7},${base + 8},${base + 9},${base + 10}::jsonb,${base + 11},${base + 12}::jsonb)`;
    });

    await pg.query(
      `insert into chat_messages (
        platform, platform_message_id, channel_id, author_id, author_name,
        author_avatar, author_color, message, message_type, badges, created_at, raw
      ) values ${rows.join(",")}
      on conflict (platform, platform_message_id) do update set
        channel_id = coalesce(excluded.channel_id, chat_messages.channel_id),
        author_id = coalesce(excluded.author_id, chat_messages.author_id),
        author_name = excluded.author_name,
        author_avatar = coalesce(excluded.author_avatar, chat_messages.author_avatar),
        author_color = coalesce(excluded.author_color, chat_messages.author_color),
        message = excluded.message,
        message_type = excluded.message_type,
        badges = case
          when jsonb_array_length(excluded.badges) > 0 then excluded.badges
          else chat_messages.badges
        end,
        created_at = excluded.created_at,
        raw = coalesce(excluded.raw, chat_messages.raw)`,
      params,
    );

    for (const message of messages) publishChatMessage(message);
    return;
  }

  const res = await fetch(
    `${supabaseUrl}/rest/v1/chat_messages?on_conflict=platform,platform_message_id`,
    {
      method: "POST",
      cache: "no-store",
      headers: {
        apikey: supabaseKey!,
        Authorization: `Bearer ${supabaseKey}`,
        "Content-Type": "application/json",
        Prefer: "resolution=merge-duplicates,return=minimal",
      },
      body: JSON.stringify(messages),
    },
  );

  if (!res.ok) {
    throw new Error(`Falha ao enriquecer mensagens: ${res.status} ${await res.text()}`);
  }

  for (const message of messages) publishChatMessage(message);
}

function activeFilters(filters?: ChannelFilters) {
  if (!filters) return [] as Array<[Platform, string]>;
  return (Object.entries(filters) as Array<[Platform, string | undefined]>)
    .filter((entry): entry is [Platform, string] => Boolean(entry[1]));
}

export async function listMessages(afterId = 0, limit = 100, filters?: ChannelFilters) {
  const filterEntries = activeFilters(filters);
  if (!dbConfigured) {
    return demoMessages.filter((m) => {
      if ((m.id || 0) <= afterId) return false;
      if (!filterEntries.length) return true;
      return filterEntries.some(([platform, channelId]) =>
        m.platform === platform && (m.channel_id === channelId || m.channel_id === "demo"));
    });
  }

  const safeLimit = Math.min(Math.max(limit, 1), 200);
  const pg = getPool();
  if (pg) {
    await ensurePgSchema();
    const params: unknown[] = [];
    const where: string[] = [];
    if (afterId > 0) {
      params.push(afterId);
      where.push(`id > $${params.length}`);
    }
    if (filterEntries.length) {
      const clauses = filterEntries.map(([platform, channelId]) => {
        params.push(platform, channelId);
        return `(platform = $${params.length - 1} and channel_id = $${params.length})`;
      });
      where.push(`(${clauses.join(" or ")})`);
    }
    params.push(safeLimit);
    const order = afterId > 0 ? "asc" : "desc";
    const result = await pg.query(
      `select * from chat_messages ${where.length ? `where ${where.join(" and ")}` : ""} order by id ${order} limit $${params.length}`,
      params,
    );
    const rows = result.rows as ChatMessage[];
    return afterId > 0 ? rows : rows.reverse();
  }

  const query = afterId > 0
    ? `chat_messages?select=*&id=gt.${afterId}&order=id.asc&limit=200`
    : `chat_messages?select=*&order=id.desc&limit=200`;
  const res = await supabaseFetch(query);
  let data = (await res.json()) as ChatMessage[];
  if (filterEntries.length) {
    data = data.filter((m) =>
      filterEntries.some(([platform, channelId]) => m.platform === platform && m.channel_id === channelId));
  }
  data = data.slice(0, safeLimit);
  return afterId > 0 ? data : data.reverse();
}

export async function getState<T>(stateKey: string): Promise<T | null> {
  if (!dbConfigured) return null;
  const pg = getPool();
  if (pg) {
    await ensurePgSchema();
    const result = await pg.query("select value from platform_state where key = $1 limit 1", [stateKey]);
    return (result.rows[0]?.value as T | undefined) ?? null;
  }
  const res = await supabaseFetch(`platform_state?select=value&key=eq.${encodeURIComponent(stateKey)}&limit=1`);
  const rows = (await res.json()) as Array<{ value: T }>;
  return rows[0]?.value ?? null;
}

export async function setState(stateKey: string, value: unknown) {
  if (!dbConfigured) return;
  const pg = getPool();
  if (pg) {
    await ensurePgSchema();
    await pg.query(
      `insert into platform_state (key, value, updated_at) values ($1, $2::jsonb, now())
       on conflict (key) do update set value = excluded.value, updated_at = now()`,
      [stateKey, JSON.stringify(value)],
    );
    return;
  }
  const res = await fetch(`${supabaseUrl}/rest/v1/platform_state?on_conflict=key`, {
    method: "POST",
    cache: "no-store",
    headers: {
      apikey: supabaseKey!,
      Authorization: `Bearer ${supabaseKey}`,
      "Content-Type": "application/json",
      Prefer: "resolution=merge-duplicates,return=minimal",
    },
    body: JSON.stringify({ key: stateKey, value, updated_at: new Date().toISOString() }),
  });
  if (!res.ok) throw new Error(`Falha ao salvar estado: ${await res.text()}`);
}

const demoMessages: ChatMessage[] = [
  {
    id: 1, platform: "twitch", platform_message_id: "demo-twitch-1", channel_id: "demo",
    author_id: "1", author_name: "pixelrunner", author_avatar: null, author_color: "#a970ff",
    message: "Esse chat junta mesmo as três plataformas?", message_type: "text", badges: [],
    created_at: new Date(Date.now() - 72000).toISOString(),
  },
  {
    id: 2, platform: "kick", platform_message_id: "demo-kick-1", channel_id: "demo",
    author_id: "2", author_name: "bruno_live", author_avatar: null, author_color: "#53fc18",
    message: "Sim! E eu posso responder usando minha conta da Kick.", message_type: "text", badges: [],
    created_at: new Date(Date.now() - 45000).toISOString(),
  },
  {
    id: 3, platform: "youtube", platform_message_id: "demo-youtube-1", channel_id: "demo",
    author_id: "3", author_name: "Ana Clips", author_avatar: null, author_color: "#ff453a",
    message: "Cheguei pelo YouTube 👋", message_type: "text", badges: [],
    created_at: new Date(Date.now() - 18000).toISOString(),
  },
];
