create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('twitch', 'kick', 'youtube')),
  platform_message_id text not null unique,
  channel_id text,
  author_id text,
  author_name text not null,
  author_avatar text,
  author_color text,
  message text not null,
  message_type text not null default 'text',
  badges jsonb not null default '[]'::jsonb,
  created_at timestamptz not null,
  raw jsonb,
  inserted_at timestamptz not null default now()
);

create index if not exists chat_messages_created_at_idx on public.chat_messages (created_at desc);
create index if not exists chat_messages_platform_idx on public.chat_messages (platform, id desc);

create table if not exists public.platform_state (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;
alter table public.platform_state enable row level security;

-- Nenhuma policy pública: somente a service role do backend acessa estas tabelas.
